### ISSUE TITLE
Support for search relation on different host/server

### ISSUE THREAD

**Issue by sairiz** [TitasGailius/nova-search-relations#28]
Hi,

Is it possible to make this searchable on multiple database on a different host/server.

So far searching on relationship base on multiple database on same server have no issue.

When i want to use it on a relationship that sits on different host/server it throws
"SQLSTATE[42S02]: Base table or view not found"

The resources and index view works perfectly though so i suspect it could work.

Thanks

**Comment by TitasGailius** [comment]
Hey,

Basically, this package only adds a bunch of `whereHas` scopes to the base search query.

Let's say we have a `User` model and a `Post` model. The user has many posts.
Given we have a `UserResource` with this configuration:

```php
/**
 * The columns that should be searched.
 *
 * @var array
 */
public static $search = ['name'];

/**
 * The relationship columns that should be searched.
 *
 * @var array
 */
public static $searchRelations = [
    'posts' => ['title'],
];
```

It all breaks down to something like this:

```php
$term = 'john';

return User::where('name', 'LIKE', "%{$term}%")
    ->orWhereHas('posts', function ($query) use ($term) {
        return $query->where('title', 'LIKE', "{$term}");
    })
    ->get();
```

Now, if the above piece of code does not work for you, there's not much I can help you with because Laravel uses subqueries to scope the related models.

```sql
SELECT * FROM users
    WHERE users.title LIKE "%john%"
       OR EXISTS (SELECT * FROM posts WHERE posts.user_id = users.id AND posts.title LIKE "%john%")
```
